apiVersion: v1
kind: Service
metadata:
  name: react-kubernetes-service
  labels:
    app: react-front-end
spec:
  type: LoadBalancer
  ports:
  - port: 80
    protocol: tcp
    targetPort: 5000
  selector:
    app: react-front-end
	
---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: react-kubernetes-deployment
spec:
  replicas: 4
  template:
    metadata:
      labels:
        app: react-front-end
    spec:
      containers:
      - name: ora-se-symposium-front-end
        image: vamsiramakrishnan/ora-se-symposium-front-end:${WERCKER_GIT_BRANCH}-${WERCKER_GIT_COMMIT}
        ports:
        - containerPort: 5000
	  protocol: tcp
