apiVersion: v1
kind: Service
metadata:
  name: react-kubernetes-service
  labels:
    app: react-front-end
spec:
  type: LoadBalancer
  ports:
  - port: 5000
    name: http
  selector:
    app: react-front-end
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: react-kubernetes-deployment
spec:
  replicas: 4
  template:
    metadata:
      labels:
        app: react-front-end

    spec:
      imagePullSecrets:
      - name: $OCIR_SECRET_NAME
      containers:
      - name: ora-se-symposium-front-end
        image: $PRIVATE_REGISTRY_PATH/$TENANCY_NAME/$REPO_NAME/$APP_NAME:${WERCKER_GIT_BRANCH}-${WERCKER_GIT_COMMIT}
        ports:
        - containerPort: 5000
